GET http://localhost:5001/
Accept: application/json

###

GET http://localhost:5001/teams
Accept: application/json

###

GET http://localhost:5001/models
Accept: application/json

###

GET http://localhost:5001/forecast?home_name=Chelsea&away_name=Burnley&league=Barclays+Premier+League&model_name=Full+simulator
Accept: application/json

###

GET http://localhost:5001/forecast-in-progress?home_name=Seattle+Sounders&away_name=Pumas+Unam&league=Major+League+Soccer&model_name=Full+simulator&minutes_elapsed=45&home_goals=1&away_goals=0
Accept: application/json

###
